In [1]:
from sklearn.ensemble import RandomForestClassifier,VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [24]:
log_clf=LogisticRegression()
rnd_clf=RandomForestClassifier()
svm_clf=SVC(probability=True)

In [25]:
voting_clf=VotingClassifier(estimators=[('lr',log_clf),('rf',rnd_clf),('svc',svm_clf)],voting='hard')

In [4]:
df=sns.load_dataset('iris')

C:\Users\lenovo\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\lenovo\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
C:\Users\lenovo\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [5]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146

In [6]:
x=df.iloc[:,:-1]

In [7]:
x.head(0)

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width]
Index: []

In [8]:
y=df.iloc[:,-1]

In [9]:
import pandas as pd
import numpy as np

In [10]:
y=pd.DataFrame(y)

In [11]:
y.head(5)

species
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [18]:
from sklearn.metrics import accuracy_score,auc,confusion_matrix,f1_score,precision_recall_curve

In [26]:
for clf in (log_clf,rnd_clf,svm_clf,voting_clf):
    clf.fit(x_train,y_train)
    ypred=clf.predict(x_test)
    print(clf.__class__.__name__,accuracy_score(y_test,ypred))
    #print(clf.__class__.__name__,auc(y_test,ypred))
    print(clf.__class__.__name__,confusion_matrix(y_test,ypred))
    #print(clf.__class__.__name__,f1_score(y_test,ypred))
    #print(clf.__class__.__name__,precision_recall_curve(y_test,ypred))
    
    

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel

LogisticRegression 1.0
LogisticRegression [[17  0  0]
 [ 0 15  0]
 [ 0  0 13]]
RandomForestClassifier 0.9555555555555556
RandomForestClassifier [[17  0  0]
 [ 0 14  1]
 [ 0  1 12]]
SVC 0.9777777777777777
SVC [[17  0  0]
 [ 0 14  1]
 [ 0  0 13]]
VotingClassifier 0.9777777777777777
VotingClassifier [[17  0  0]
 [ 0 14  1]
 [ 0  0 13]]


C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [31]:
voting_clf=VotingClassifier(estimators=[('lr',log_clf),('rf',rnd_clf),('svc',svm_clf)],voting='soft',weights=[2,3,4],
    n_jobs=-1)

In [32]:
for clf in (log_clf,rnd_clf,svm_clf,voting_clf):
    clf.fit(x_train,y_train)
    ypred=clf.predict(x_test)
    print(clf.__class__.__name__,accuracy_score(y_test,ypred))
    #print(clf.__class__.__name__,auc(y_test,ypred))
    print(clf.__class__.__name__,confusion_matrix(y_test,ypred))
    #print(clf.__class__.__name__,f1_score(y_test,ypred))
    #print(clf.__class__.__name__,precision_recall_curve(y_test,ypred))
    
    

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\utils\

LogisticRegression 1.0
LogisticRegression [[17  0  0]
 [ 0 15  0]
 [ 0  0 13]]
RandomForestClassifier 0.9777777777777777
RandomForestClassifier [[17  0  0]
 [ 0 14  1]
 [ 0  0 13]]
SVC 0.9777777777777777
SVC [[17  0  0]
 [ 0 14  1]
 [ 0  0 13]]
VotingClassifier 0.9777777777777777
VotingClassifier [[17  0  0]
 [ 0 14  1]
 [ 0  0 13]]


In [35]:
voting_clf=VotingClassifier(estimators=[('lr',log_clf),('rf',rnd_clf),('svc',svm_clf)],voting='soft',
    n_jobs=-1)

In [36]:
for clf in (log_clf,rnd_clf,svm_clf,voting_clf):
    clf.fit(x_train,y_train)
    ypred=clf.predict(x_test)
    print(clf.__class__.__name__,accuracy_score(y_test,ypred))
    #print(clf.__class__.__name__,auc(y_test,ypred))
    print(clf.__class__.__name__,confusion_matrix(y_test,ypred))
    #print(clf.__class__.__name__,f1_score(y_test,ypred))
    #print(clf.__class__.__name__,precision_recall_curve(y_test,ypred))
    
    

C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  
C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\utils\

LogisticRegression 1.0
LogisticRegression [[17  0  0]
 [ 0 15  0]
 [ 0  0 13]]
RandomForestClassifier 0.9777777777777777
RandomForestClassifier [[17  0  0]
 [ 0 14  1]
 [ 0  0 13]]
SVC 0.9777777777777777
SVC [[17  0  0]
 [ 0 14  1]
 [ 0  0 13]]
VotingClassifier 0.9777777777777777
VotingClassifier [[17  0  0]
 [ 0 14  1]
 [ 0  0 13]]
